apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}
  namespace: default
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
          - env:
            - name: JIRA_API_TOKEN
              valueFrom:
                secretKeyRef:
                  key: JIRA_API_TOKEN
                  name: {{ .Chart.Name }}-secrets
            - name: SLACK_AK
              valueFrom:
                secretKeyRef:
                  key: SLACK_AK
                  name: {{ .Chart.Name }}-secrets
            - name: SLACK_SK
              valueFrom:
                secretKeyRef:
                  key: SLACK_SK
                  name: {{ .Chart.Name }}-secrets
            - name: AGW_API_KEY
              valueFrom:
                secretKeyRef:
                  key: AGW_API_KEY
                  name: {{ .Chart.Name }}-secrets
            image: {{ .Values.image.repo }}/{{ .Values.image.name }}:latest
            imagePullPolicy: IfNotPresent
            name: {{ .Chart.Name }}
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - name: config-volume
              mountPath: /usr/src/app/src/config/
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - name: config-volume
            configMap:
              name: {{ .Chart.Name }}-configmap
  schedule: '0 */8 * * *'
  suspend: false